from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()

# Title
title = doc.add_heading('One-Page Assignment Report', 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

# Header Info
doc.add_paragraph('Course: SE803 Software Project Management').bold = True

group_info = doc.add_paragraph()
group_info.add_run('Group Members:\n').bold = True
group_info.add_run('1. Name: Hasin Ahmed | Roll: BSSE1415\n')
group_info.add_run('2. Name: Nazmus Shakib | Roll: BSSE1452\n')

link = doc.add_paragraph()
link.add_run('GitHub Link: ').bold = True
link.add_run('https://github.com/Hasin-ai/liquid-ai-chatbot-assignment')

# Project Summary
doc.add_heading('Project Summary', level=1)
p1 = doc.add_paragraph(
    "This assignment implements a small LLM-powered chatbot system using an open-source lightweight AI model (Liquid AI LFM model served via Ollama). "
    "The system includes a secure login-based authentication process where each user must sign in to access the chatbot. "
    "After successful login, the user can ask any question to the chatbot and receive responses generated by the model."
)

# Architecture and Features
doc.add_heading('Architecture and Features', level=1)
p2 = doc.add_paragraph(
    "The frontend is built using React and styled to mimic a clean, modern Gemini-like interface. "
    "The backend is built with FastAPI, utilizing JWT authentication to secure the chat route. "
    "To fulfill the assignment requirements, a comprehensive chat-history storage mechanism was implemented using SQLite and Qdrant. "
    "All conversations are persistently saved under each user’s account. "
    "When a user returns and logs in again, they are able to view their entire previous chat history seamlessly from a dedicated sidebar. "
    "The system achieves the full requested workflow: authentication, model integration through LangChain, a functional chat interface, and persistent storage of conversations."
)

# Outcome
doc.add_heading('Outcome', level=1)
p3 = doc.add_paragraph(
    "The completed system successfully fulfills all requirements of the SE803 assignment. "
    "Users can create accounts, log in securely, interact with a local open-source LLM, and seamlessly revisit their past chats thanks to the robust persistent storage backend."
)

# Save
doc.save('REPORT.docx')
print("Report generated successfully at REPORT.docx")
